stages:
  - build
  - test

variables:
  DB_URL: "jdbc:postgresql://db:5432/mspr1db"
  DB_USERNAME: "mspr1"
  DB_PASSWORD: "mspr1"

build-backend:
  stage: build
  image: maven:3.9.9-amazoncorretto-21-debian
  script:
    - cd backend
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar
    expire_in: 1 week
  only:
    - main
    - merge_requests

test-backend:
  stage: test
  image: maven:3.9.9-amazoncorretto-21-debian
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: mspr1db
    POSTGRES_USER: mspr1
    POSTGRES_PASSWORD: mspr1
    DB_URL: "jdbc:postgresql://postgres:5432/mspr1db"
    DB_USERNAME: "mspr1"
    DB_PASSWORD: "mspr1"
  script:
    - cd backend
    - mkdir -p src/test/resources
    - cp .env src/test/resources/.env
    - mvn test
  only:
    - main
    - merge_requests

build-frontend:
  stage: build
  image: node:20-alpine
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 week
  only:
    - main
    - merge_requests
