stages:
  - build
  - test

variables:
  DB_URL: "jdbc:postgresql://db:5432/mspr1db"
  DB_USERNAME: "mspr1"
  DB_PASSWORD: "mspr1"
  DB_NAME: "mspr1db"
  DB_PORT: "5432"

build-backend:
  stage: build
  image: maven:3.9.9-amazoncorretto-21-debian
  script:
    - cd backend
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar
    expire_in: 1 week
  only:
    - main
    - merge_requests

build-frontend:
  stage: build
  image: node:20-alpine
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 week
  only:
    - main
    - merge_requests

test-backend:
  stage: test
  image: maven:3.9.9-amazoncorretto-21-debian
  services:
    - name: postgres:latest
      alias: db
  variables:
    POSTGRES_DB: ${DB_NAME}
    POSTGRES_USER: ${DB_USERNAME}
    POSTGRES_PASSWORD: ${DB_PASSWORD}
  script:
    - cd backend
    - echo "Testing with database URL ${DB_URL}"
    - mvn test
  only:
    - main
    - merge_requests
